server:
  port: 80
  servlet:
    application-display-name: Graduation
  max-http-request-header-size: 32KB
spring:
  security:
    user:
      name: user
      password: password
  cache:
    cache-names: menus
    caffeine.spec: maximumSize=5000,expireAfterAccess=600s
springdoc:
  packagesToScan: com.pafolder.graduation.controller
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
  version: '@springdoc.version@'
level: warn
logging:
  level:
    ROOT: ${level}
    org:
      hibernate: ${level}
      hibernate.SQL: ${level}
      springframework:
        cache: ${level}
        orm:
          jpa: ${level}
        transaction: ${level}
        transaction.interceptor: ${level}

