rva:
  version: 0.95
  tomcat:
    script:
      user: user
      password: password

spring:
  datasource:
    username: sa
    password: ''
    url: jdbc:hsqldb:mem:graduation
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  cache:
    cache-names: menus, users
    caffeine.spec: maximumSize=5000,expireAfterAccess=3d
server:
  port: 80
  max-http-request-header-size: 32KB
  servlet:
    application-display-name: RVA Graduation project
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc:
  packagesToScan: com.pafolder.graduation.controller
  swagger-ui:
    path: /
    defaultModelsExpandDepth: -1
    tagsSorter: alpha
logging:
  level:
    ROOT: warn

