rva:
  tomcat:
    script:
      user: user
      password: password
spring:
  datasource:
    username: sa
    password: ''
    url: jdbc:hsqldb:mem:graduation
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  cache:
    cache-names: menus
    caffeine.spec: maximumSize=5000,expireAfterAccess=600s
server:
  port: 80
  servlet:
    application-display-name: Graduation
  max-http-request-header-size: 64KB
springdoc:
  packagesToScan: com.pafolder.graduation.controller
  swagger-ui:
    path: /swagger-ui
    tagsSorter: alpha
  version: '@springdoc.version@'
level: error
logging:
  level:
    ROOT: ${level}
    org:
      hibernate: ${level}
      hibernate.SQL: ${level}
      springframework:
        cache: trace
        orm:
          jpa: ${level}
        transaction: trace
        transaction.interceptor: ${level}
